<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dong</groupId>
        <artifactId>dzdp-plus</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>dzdp-mq-framework</artifactId>
    <name>dzdp-mq-framework</name>
    <description>mq封装</description>
    <packaging>pom</packaging>

    <modules>
        <module>dzdp-mq-common-framework</module>
        <module>dzdp-mq-producer-framework</module>
        <module>dzdp-mq-consumer-framework</module>
    </modules>

</project>
